// Create user
POST http://192.168.171.180:3001/users/register
Content-Type: application/json

{
    "userEmail": "hanna@gmail.com",
    "userName": "Hanna",
    "userPassword": "test"
}

###

// Login
POST http://192.168.171.180:3001/users/login
Content-Type: application/json

{
    "userName": "",
    "userPassword": ""
}

###

// MESSAGES SECTION

POST http://192.168.171.180:3001/messages
Content-Type: application/json

{
    "id": "65c4d160d9c96b34c92b8edd"    
}

###

//Get all messages:
GET http://192.168.171.180:3001/messages
Content-Type: application/json

###

//Add new message:
POST http://192.168.171.180:3001/messages/add
Content-Type: application/json

{
    "userName": "",
    "userMessage": ""
  }

###

//All messages from one specific user:
POST http://192.168.171.180:3001/messages/display
Content-Type: application/json

{
    "userName": "Kalle"
}

###